version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: main
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
