[package]
name = "servio-http"
version = "0.1.0"
description = "HTTP types for Servo"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
bytes = "1.2.1"
http = "0.2.8"
