[package]
name = "servio-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
servio = { path = "../servio" }
futures-core = "0.3.25"
tracing = "0.1"
futures-util = "0.3.25"
